- name : Install Nginx
  hosts: webservers
  become: yes
  tasks:
    - name: Install Nginx
      ansible.builtin.package:
        name: nginx
        state: present

    - name: Start Nginx service
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes    

    - name: Remove default Nginx index.html
      ansible.builtin.file:
        path: /usr/share/nginx/html/index.html
        state: absent

    - name: Copy index.html file
      ansible.builtin.copy:
        src: index.html
        dest: /usr/share/nginx/html
        mode: '0755'

    - name: Restart Nginx service
      ansible.builtin.service:
        name: nginx
        state: restarted