- name : Install Nginx
  hosts: webservers
  become: yes
  tasks:
    - name: Install Nginx
      ansible.builtin.package:
        name: nginx
        state: present

- name: Start Nginx service
  hosts: webservers
  become: yes
  tasks:
    - name: Start Nginx service
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes

- name: Check Nginx status
  hosts: webservers
  become: yes
  tasks:
    - name: Check Nginx status
      ansible.builtin.service:
        name: nginx
        state: started

- name : remove default Nginx index.html
  hosts: webservers
  become: yes
  tasks:
    - name: Remove default Nginx index.html
      ansible.builtin.file:
        path: /var/www/html/index.html
        state: absent

- name: Copy index.html file
  hosts: webservers
  become: yes
  tasks:
    - name: Copy index.html file
      ansible.builtin.copy:
        src: index.html
        dest: /var/www/html/index.html
        mode: '0644'

- name: Restart Nginx service
  hosts: webservers
  become: yes
  tasks:
    - name: Restart Nginx service
      ansible.builtin.service:
        name: nginx
        state: restarted