- name : Install Nginx
  hosts: webservers
  become: yes
  tasks:
    - name: Install Nginx
      ansible.builtin.package:
        name: nginx
        state: present

- name: Start Nginx service
  hosts: webservers
  become: yes
  tasks:
    - name: Start Nginx service
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes