- name : Print my name
  hosts: webservers
  vars_files:
    - cource.yaml   
  tasks:
    - name: Print my name
      vars:
        course: "Python"
      debug:
        msg: "My name is {{ First_Name }} and I am taking the {{ course }} course for {{ duration }}. The class starts at {{ time }}."