- name : checking the vars prefernce
  hosts: webservers
  vars:
    last_Name: "Venky"
  #vars_files:
    #- course.yaml

  #vars_prompt:
    #- name: "last_Name"
    #  prompt: "Please enter your name"
    #  private: no
    
  tasks:
    - name: Print my name
      #vars:
        #last_Name: "John Doe"
      debug:
        msg: "hi {{ last_Name }}"