- name : Print my name
  hosts: webservers
  vars:
   First_Name: "John Doe"
   course: "Ansible"
   duration: "2 weeks"
   time : "10:00 AM"
  tasks:
    - name: Print my name
      debug:
        msg: "My name is {{ First_Name }} and I am taking the {{ course }} course for {{ duration }}. The class starts at {{ time }}."